### PR TITLE
adding style and layouts to the background and gradients project

### PR DESCRIPTION
**Pull request by rubenpazch**
I work on project Apple old site and making use of background and gradient, finally, I used Float, positioning, grid, and flexbox.

### CODE REVIEW

**Comment by shshamim63** [comment]
## Status :waning_gibbous_moon: [Changes Required] :waning_gibbous_moon: 
___
Hi @rubenpazch :wave: 
Code looks neat and clean. No linter errors, neither errors on html markup validation. Repository contains readme. Awesome job :clap: . But some issues are blocking me to approve this project. And I believe you will cover them easily.
___
### :spades: [Mandatory Changes] :spades: 
___
1. Bottom: It contains four elements which are links (to another articles or #). If you inspect the [original page](https://web.archive.org/web/20140301004610/http://www.apple.com/). you will see that those are enclosed inside a tag.
2. Description on readme is contains a simple typo mistake.
This project consists of building a webpage using images as a background and adding gradients to elements. The goal is to make a clone of **`old an old version`** of the Apple website webpage. You meant of an old version right?
3. PR summary also contains a typo mistake->
`also **son** float, positioning, grid, and flexbox.`
You mean utilize of float, positioning, grid, and flexbox. right? 

___
### :clubs: Optional Change :clubs: 
1. Comparing to the actual one I think the nabvar should be a little bit wider.
Your one ->
image
Actual One ->
image
___
#### Please fix the above mentioned issues and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

**Comment by rubenpazch** [comment]
Hi, @shshamim63  thank you for your recommendations, I think there were some grammar mistakes so I fixed it.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @rubenpazch, great work:+1:. We are almost there.**

You have missed only one of the changes required by @shshamim63 . The four images at the bottom should be links. Enclose them in anchor tags.

_**Please make this change and submit another code review request.**_

**Cheers:smile:**

**Status: Changes requested**

**Review by mosesogwo — APPROVED** [review]
### :trophy:Congratulations @rubenpazch. Your project is now approved!.

Please go ahead and merge to master.

**Good luck in your next project:smile:**

**Status: Approved!**

**Pull request merged**
